baseURL = 'https://jainilv1.netlify.app/'
languageCode = 'en-us'
title = ''
theme = "PaperMod" 


[params]
  defaultTheme = "dark"  # Forces dark mode
  disableThemeToggle = true  # Removes the light/dark switcher
  customCSS = "css/extended/custom.css"

sectionPagesMenu = ""

publishDir = "public"

[params.assets]
  disableFingerprinting = true


  