name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Change to 'master' if your default branch is 'master'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Install dependencies
        run: sudo apt-get install -y git

      - name: Build site
        run: hugo --minify
        env:
          HUGO_ENV: production  # Ensure production environment is used

      # ✅ Debug Step: Check if `public/` directory is created
      - name: List generated files
        run: ls -la public

      # Upload artifact if the build was successful
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public  # Ensure Hugo output is correctly referenced

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
